name: Pylint Checks

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.88
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pylint
      run: |
        python -m pip install --upgrade pylint
    - name: Lint code
      run: |
        pylint -r y mongars
